<a href="https://colab.research.google.com/github/ridvanyigit/PyTorch/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cheat Sheet of Top Useful **PyThorch** Methods

In [3]:
import torch

## torch.tensor
* Description : The torch.tensor method used to create a tensor from data. It's one of the most fundamental operations in PyTorch

In [4]:
# Create a tensor from a list
data = [1,2,3,4]
tensor = torch.tensor(data)
tensor

tensor([1, 2, 3, 4])


## torch.zeros
* Description : The torch.zeros method returns a tensor filled with zeros. The shape of tensor is defined by the input arguments.

In [6]:
# Create a 2x3 tensor filled with zeros
zeros_tensor = torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## torch.ones
* Description : The torch.ones method returns a tensor filled with ones. The shape of tensor is defined by the input arguments.

In [7]:
# Create a 2x3 tensor filled with ones
ones_tensor = torch.ones(2,3)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## torch.rand
* Description : The torch.rand method returns a tensor filled with random numbers between 0 and 1

In [8]:
# Create a 3x3 tensor filled with random numbers between 0 and 1
rand_tensor = torch.rand(3,3)
rand_tensor

tensor([[0.2979, 0.0876, 0.2316],
        [0.6530, 0.7034, 0.7121],
        [0.3448, 0.3924, 0.6140]])

## torch.randn
* Description : The torch.rand method returns a tensor filled with random numbers from a normal distribution

In [9]:
# Create a 2x3 tensor filled with random numbers from a normal distribution
randn_tensor = torch.randn(2,3)
randn_tensor

tensor([[-0.5468, -0.0509, -0.1833],
        [-0.1048, -0.1554, -0.9786]])

## torch.linspace
* Distribution : The torch.linspace method retuns a 1D tensor with values spaced linearly within a given interval

In [10]:
# Create a tensor with 5 values spaced linearly between 0 and 10
linspace_tensor = torch.linspace(0, 10, steps=5)
linspace_tensor

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

## torch.arange
* Description : The torch.arange method returns a 1D tensor with values spaced by a given step size

In [11]:
# Create a tensor with values from 0 to 10 with a step size of 2
arange_tensor = torch.arange(0, 10, step=2)
arange_tensor

tensor([0, 2, 4, 6, 8])

## torch.eye
* Description : The torch.eye method returns a 2D tensor with ones on the diagonal and zeros elsewhere (an identity matrix)

In [12]:
# Create a 3x3 identity matrix
eye_tensor = torch.eye(3)
eye_tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## torch.matmul
* Description : The torch.matmul method performs matrix multiplication between two tensors

In [13]:
# Define two 2D tensors
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5,6],[7,8]])

# Perform matrix multiplication
matmul_result = torch.matmul(tensor1,tensor2)
matmul_result

tensor([[19, 22],
        [43, 50]])

## torch.mm
* Description : The torch.mm method is similar to torch.matmul, but specifically for 2D tensors

In [14]:
# Define two 2D tensors
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5,6],[7,8]])

# Perform matrix multiplication
mm_result = torch.mm(tensor1,tensor2)
mm_result

tensor([[19, 22],
        [43, 50]])

## torch.bmm
* Description : The torch.bmm method performs batch matrix multiplication

In [15]:
# Define two 3D tensors
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)

# Perform batch matrix multiplication
bmm_result = torch.bmm(tensor1, tensor2)
bmm_result

tensor([[[ 0.1233, -1.0812, -1.6761,  2.2863,  2.1215],
         [ 0.1125,  0.3183,  0.9591,  0.4328, -1.0418],
         [ 1.5182, -1.6515, -1.4561, -2.3375, -1.3022]],

        [[ 0.0670,  0.6765, -0.3750,  1.4633, -1.6344],
         [ 1.0787, -0.4239,  0.4056, -3.6803,  1.0330],
         [ 0.8893, -1.5297,  2.2400, -2.7689, -1.7993]],

        [[ 0.5919,  0.7290, -0.7223,  2.0388,  1.2171],
         [-0.2954, -1.4657, -0.9653,  0.8342,  0.7763],
         [ 0.5102,  0.0721, -1.3102,  2.9845, -2.0000]],

        [[ 0.1626,  1.2960,  1.0410,  0.2144, -0.9684],
         [-1.1223, -0.1140, -0.1872, -0.5601, -0.4452],
         [-0.4820,  2.7764,  2.3345,  0.6487,  0.4280]],

        [[-0.2534, -1.4942, -4.3620,  3.9280,  3.5845],
         [ 1.2017, -0.7696, -1.5643,  0.9957,  1.0627],
         [-2.4893,  0.0669,  1.9810, -0.7139, -1.0233]],

        [[-4.7130, -2.8648, -1.0848,  0.4785,  0.5026],
         [-2.6835, -1.6699, -0.8045,  1.7950, -0.3130],
         [-4.0427, -3.3244, -2.4697, -

## torch.cat
* Desription : The torch.cat method concatenates a sequence of tensors along a specified dimension

In [16]:
# Define two tensors
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5,6]])

# Concatenate alonge the first dimension
cat_result = torch.cat((tensor1, tensor2), dim=0)
cat_result

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## torch.stack
* Description : The torch.stack method stacks a sequence of tensors alonge a new dimension

In [17]:
# Define two tensors
tensor1 = torch.tensor([1,2])
tensor2 = torch.tensor([3,4])

# Stack alonge a new dimension
stack_result = torch.stack((tensor1, tensor2), dim=0)
stack_result

tensor([[1, 2],
        [3, 4]])

## torch.split
* Description : The torch.split method splits a tensor into chunks

In [18]:
# Define two tensors
tensor1 = torch.tensor([1,2,3,4,5,6])

# Split into three chunks
split_result = torch.split(tensor, 2)
for chunk in split_result:
  print(chunk)

tensor([1, 2])
tensor([3, 4])


## torch.chunk
* Description : The torch.chunk method splits a tensor into a specified number of chunks

In [19]:
# Define two tensors
tensor1 = torch.tensor([1,2,3,4,5,6])

# Chunk the tensor into three parts
chunk_result = torch.chunk(tensor, 3)
for chunk in chunk_result:
  print(chunk)

tensor([1, 2])
tensor([3, 4])


## torch.reshape
* Description : The torch.reshape method returns a tensor with a new shape, without changing the data

In [20]:
# Define a tensor
tensor = torch.tensor([[1,2,3],[4,5,6]])

# Reshape the tensor to a different shape
reshape_result = torch.reshape(tensor, (3,2))
reshape_result

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## tensor.view
* Description : The tensor.view method returns a new tensor with the same data but a different shape

In [21]:
# Define a tensor
tensor = torch.tensor([[1,2,3],[4,5,6]])

# View the tensor with a different shape
view_result = tensor.view(3,2)
view_result

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## torch.transpose
* Description : The torch.transpose method returns a tensor with dimensions transposed

In [22]:
# Define a tensor
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

# Transpose the tensor
transpose_result = torch.transpose(tensor, 0, 1)
transpose_result

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

## torch.t
* Description : The torch.t method transposes the last two dimensions of a tensor

In [23]:
# Define a tensor
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

# Transpose the last two dimensions
t_result = torch.t(tensor)
t_result

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

## torch.permute
* Description : The torch.permute method permutes the dimensions of a tensor

In [24]:
# Define a 3D tensor
tensor = torch.randn(2,3,4)

# Permute the dimensions
permute_result = torch.permute(tensor,(2,0,1))
permute_result.size()

torch.Size([4, 2, 3])

## torch.unsqueeze
* Description : The torch.unsqueeze method returns a tensor with a dimension of size one inserted at the specified position

In [25]:
# Define a tensor
tensor = torch.tensor([1,2,3,4])

# Unsqueeze the tensor to add a new dimension
unsqueeze_result = torch.unsqueeze(tensor, dim=0)
unsqueeze_result

tensor([[1, 2, 3, 4]])

## torch.squeeze
* Description : The torch.sequeeze method returns a tensor with all the dimensions of size 1 removed

In [26]:
# Define a tensor
tensor = torch.tensor([[[1, 2, 3, 4]]])

# Squeeze the tensor to remove dimensions of size 1
squeeze_result = torch.squeeze(tensor)
squeeze_result

tensor([1, 2, 3, 4])

## torch.flatten
* Description : The torch.flatten method flattens a tensor to a single dimension

In [27]:
# Define a 2D tensor
tensor = torch.tensor([[1,2,3],[4,5,6]])

# Flatten the tensor
flatten_result = torch.flatten(tensor)
flatten_result

tensor([1, 2, 3, 4, 5, 6])

## torch.norm
* Description : The torch.norm method returns the norm of a tensor

In [28]:
# Define a tensor
tensor = torch.tensor([1,2,3,4], dtype=torch.float32)

# Calculate the norm of the tensor
norm_result = torch.norm(tensor)
norm_result

tensor(5.4772)

## torch.max
* Description : The torch.max method returns the maximum value of all elements in a tensor

In [29]:
# Define a tensor
tensor = torch.tensor([[1,2],[3,4]])

# Find the maximum value
max_result = torch.max(tensor)
max_result

tensor(4)

## torch.min
* Description : The torch.max method returns the minimum value of all elements in a tensor

In [30]:
# Define a tensor
tensor = torch.tensor([[1,2],[3,4]])

# Find the minimum value
min_result = torch.min(tensor)
min_result

tensor(1)

## torch.sum
* Desctiprion : The torch.sum method returns sum of the all elements in a tensor

In [31]:
# Define a tensor
tensor = torch.tensor([[1,2],[3,4]])

# Find the sum of all elemants
sum_result = torch.sum(tensor)
sum_result

tensor(10)

## torch.mean
* Description : The torch.mean method returns the mean of all elements in a tensor

In [32]:
# Define a tensor
tensor = torch.tensor([[1,2],[3,4]], dtype=torch.float32)

# Find the mean of all elements
mean_result = torch.mean(tensor)
mean_result

tensor(2.5000)

## torch.std
* Description : The torch.std method returns the standard deviation of all elements in a tensor

In [33]:
# Define a tensor
tensor = torch.tensor([[1,2],[3,4]], dtype=torch.float32)

# Find the standard deviation of all elements
std_result = torch.std(tensor)
std_result

tensor(1.2910)

## torch.var
* Description : The torch.std method returns the variance of all elements in a tensor

In [34]:
# Define a tensor
tensor = torch.tensor([[1,2],[3,4]], dtype=torch.float32)

# Find the variance of all elements
var_result = torch.var(tensor)
var_result

tensor(1.6667)

## torch.argmax
* Description : The torch.argmax method returns the indices of the maximum value of all elements along a specified axis

In [35]:
# Define a tensor
tensor = torch.tensor([[1,2],[3,4]])

# Find the index of the maximum value
argmax_result = torch.argmax(tensor)
argmax_result

tensor(3)

## torch.argmin
* Description : The torch.argmin method returns the indices of the maximum value of all elements along a specified axis

In [36]:
# Define a tensor
tensor = torch.tensor([[1,2],[3,4]])

# Find the index of the minimum value
argmin_result = torch.argmin(tensor)
argmin_result

tensor(0)

## torch.nn.Linear
* Description : The torch.nn.Linear method creates a fully connected layer in a neural network

In [37]:
import torch.nn as nn

In [38]:
# Define a fully connected layer
linear = nn.Linear(in_features=2, out_features=3)

# Define an input tensor
input_tensor = torch.tensor([[1.0, 2.0]])

# Pass the input tensor through the linear layer
output_tensor = linear(input_tensor)
output_tensor

tensor([[-1.2984,  0.3009,  1.5287]], grad_fn=<AddmmBackward0>)

## torch.nn.Conv2d
* Description : The torch.Conv.2d method creates a 2D convolutional layer in a neural network

In [39]:
# Define a 2D convolutional layer
conv2d = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3)

# Define an input tensor
input_tensor = torch.randn(1,1,5,5)

# Pass the input tensor through the convolutional layer
output_tensor = conv2d(input_tensor)
output_tensor.size()

torch.Size([1, 1, 3, 3])

## torch.nn.ReLU
* Description : The torch.nn.ReLU method applies the ReLU activation function in a neural network

In [40]:
# Define a ReLU activation function
relu = nn.ReLU()

# Define an input tensor
input_tensor = torch.tensor([-1.0, 0.0, 1.0])

# Apply the ReLU activation function
output_tensor = relu(input_tensor)
output_tensor

tensor([0., 0., 1.])

## torch.nn.Sigmoid
* Description : The torch.nn.Sigmoid method applies the Sigmoid activation function in a neural network

In [41]:
# Define a ReLU activation function
sigmoid = nn.Sigmoid()

# Define an input tensor
input_tensor = torch.tensor([-1.0, 0.0, 1.0])

# Apply the Sigmoid activation function
output_tensor = sigmoid(input_tensor)
output_tensor

tensor([0.2689, 0.5000, 0.7311])

## torch.nn.CrossEntropyLoss
* Description : The torch.nn.CrossEntropyLoss method creates a cross-entropy loss function for classification problem

In [42]:
## Define a Cross-Entropy loss function
loss_fn = nn.CrossEntropyLoss()

# Define the inputs (logits) and target labels
inputs = torch.tensor([[0.5, 1.5, 2.0]])
targets = torch.tensor([2])

# Compute the loss
loss = loss_fn(inputs, targets)
loss

tensor(0.6041)

## torch.nn.MSELoss
* Description : The torch.nn.MSELoss method creates a mean squared error loss function for regression problems

In [43]:
# Define a mean squared error loss function
loss_fn = nn.MSELoss()

# Define the inputs and target labels
inputs = torch.tensor([[0.5, 1.5, 2.0]])
targets = torch.tensor([[1.0, 2.0, 3.0]])

# Compute the loss
loss = loss_fn(inputs, targets)
loss

tensor(0.5000)

## torch.optim.SGD
* Description : The torch.optim.SGD method creates a stochastic gradient descent optimizer

In [44]:
import torch.optim as optim

In [45]:
# Define a simple linear model
model = nn.Linear(in_features=2, out_features=1)

# Define a stochastic gradient descent optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Define a simple input tensor a target
input_tensor = torch.tensor([[1.0, 2.0]])
target = torch.tensor([[1.0]])

# Forward Pass
output = model(input_tensor)

# Compute loss
loss = nn.MSELoss()(output, target)

# Backward pass and optimize
optimizer.zero_grad()
loss.backward()
optimizer.step()

output

tensor([[0.6708]], grad_fn=<AddmmBackward0>)

## torch.optim.Adam
* Description : The torch.optim.Adam method creates a Adam optimizer

In [46]:
# Define a simple linear model
model = nn.Linear(in_features=2, out_features=1)

# Define a stochastic gradient descent optimizer
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Define a simple input tensor a target
input_tensor = torch.tensor([[1.0, 2.0]])
target = torch.tensor([[1.0]])

# Forward Pass
output = model(input_tensor)

# Compute loss
loss = nn.MSELoss()(output, target)

# Backward pass and optimize
optimizer.zero_grad()
loss.backward()
optimizer.step()

output

tensor([[-0.1108]], grad_fn=<AddmmBackward0>)

## torch.optim.lr_scheduler.StepLR
* Description : The torch.optim.lr_scheduler.StepLR method creates a learning rate scheduler that decays the learning rate by a factor every few epochs

In [47]:
# Define a simple linear model
model = nn.Linear(in_features=2, out_features=1)

# Define a stochastic gradient descent optimizer
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Define a learning rate scheduler
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.1)

# Define a simple input tensor a target
input_tensor = torch.tensor([[1.0, 2.0]])
target = torch.tensor([[1.0]])

# Training loop
for epoch in range(20):

  # Forward Pass
  output = model(input_tensor)

  # Compute loss
  loss = nn.MSELoss()(output, target)

  # Backward pass and optimize
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  # Step the learning rate scheduler
  scheduler.step()

  print(f'Epoch {epoch+1}, Loss: {loss.item()}, LR: {scheduler.get_last_lr()}')

Epoch 1, Loss: 0.3337379992008209, LR: [0.01]
Epoch 2, Loss: 0.28912192583084106, LR: [0.01]
Epoch 3, Loss: 0.24780584871768951, LR: [0.01]
Epoch 4, Loss: 0.2098376601934433, LR: [0.01]
Epoch 5, Loss: 0.17524853348731995, LR: [0.01]
Epoch 6, Loss: 0.14405009150505066, LR: [0.01]
Epoch 7, Loss: 0.11623126268386841, LR: [0.01]
Epoch 8, Loss: 0.09175535291433334, LR: [0.01]
Epoch 9, Loss: 0.07055686414241791, LR: [0.01]
Epoch 10, Loss: 0.052538707852363586, LR: [0.001]
Epoch 11, Loss: 0.03757016733288765, LR: [0.001]
Epoch 12, Loss: 0.03625647351145744, LR: [0.001]
Epoch 13, Loss: 0.035004377365112305, LR: [0.001]
Epoch 14, Loss: 0.033806782215833664, LR: [0.001]
Epoch 15, Loss: 0.03265800699591637, LR: [0.001]
Epoch 16, Loss: 0.031553395092487335, LR: [0.001]
Epoch 17, Loss: 0.03048911690711975, LR: [0.001]
Epoch 18, Loss: 0.029461897909641266, LR: [0.001]
Epoch 19, Loss: 0.028469055891036987, LR: [0.001]
Epoch 20, Loss: 0.027508292347192764, LR: [0.0001]


## torch.autograd.grad
* Description : The torch.autograd.grad method computes and returns the gradients of specified tensors

In [48]:
# Define a simple function
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2

# Compute gradients
grad = torch.autograd.grad(outputs=y, inputs=x)
grad

(tensor(4.),)

## torch.autograd.backward
* Description : The torch.autograd.backward method computes the gradient of the current tensor w.r.t. graph leaves

In [49]:
# Define a simple function
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2

# Perform backpropagation
y.backward()

# Print the gradient
x.grad

tensor(4.)

## torch.cuda.is_available
* Description : The torch.cuda.is_available method returns a boolean indicating wheter CUDA is available for GPU acceleration

In [50]:
# Check if CUDA is available
cuda_available = torch.cuda.is_available()
print(cuda_available)

False


## torch.cuda.device
* Description : The torch.cuda.device method is a context manager for selecting a CUDA device

In [51]:
if torch.cuda.is_available():
    with torch.cuda.device(0):
        tensor = torch.tensor([1, 2, 3], device='cuda')
        print(tensor)
else:
    print("GPU not available.")

GPU not available.


## torch.save
* Description : The torch.save method saves an object to a disk file

In [52]:
# Define a simple tensor
tensor = torch.tensor([1,2,3])

# Save the tensor from a file
torch.save(tensor, 'tensor.pth')

## torch.load
* Description : The torch.load method loads an object saved with torch.save from a disk file

In [53]:
# Load the tensor from a file
tensor = torch.load('tensor.pth')
tensor

<ipython-input-53-c12e81608f9f>:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  tensor = torch.load('tensor.pth')


tensor([1, 2, 3])

## torch.nn.Module
* Description : The torch.nn.Module method is the base class for all neural network modules

In [54]:
# Define a simple neural network
class SimpleNN(nn.Module):
  def __init__(self):
    super(SimpleNN, self).__init__()
    self.fc1 = nn.Linear(2,2)
    self.fc2 = nn.Linear(2,1)

    def forward(self,x):
      x = self.fc1(x)
      x = torch.relu(x)
      x = self.fc2(x)
      return x

# Instantiate the neural network
model = SimpleNN()
model

SimpleNN(
  (fc1): Linear(in_features=2, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=1, bias=True)
)

## torch.nn.Sequential
* Description : The torch.nn.Sequential method is a sequential container to stack multiple layers

In [55]:
# Define a simple sequential model
model = nn.Sequential(
    nn.Linear(2,2),
    nn.ReLU(),
    nn.Linear(2,1)
)
model

Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): ReLU()
  (2): Linear(in_features=2, out_features=1, bias=True)
)

## torch.nn.Dropout
* Description : The torch.nn.Dropout method creates a dopout layer that randomly zeroes some of the elements of the input tensor with a probability

In [56]:
# Define a dopout layer
dropout = nn.Dropout(p=0.5)

# Define an input tensor
input_tensor = torch.randn(2,3)

# Apply dropout
output_tensor = dropout(input_tensor)
output_tensor

tensor([[-0.0000, -0.0000,  3.0848],
        [-0.7464,  0.8967, -0.9492]])

## torch.nn.BatchNorm2d
* Description : The torch.nn.BatchNorm2d method creates a layer that normalizes the input for each mini-batch

In [57]:
# Define a batch normalization layer
batch_norm = nn.BatchNorm2d(num_features=3)

# Define an input tensor
input_tensor = torch.randn(2,3,4,5)

# Apply batch normalization
output_tensor = batch_norm(input_tensor)
output_tensor

tensor([[[[-0.0055, -1.5178,  0.2924, -0.3165,  1.2437],
          [-0.2288, -1.0512,  1.3020, -1.1500,  0.7707],
          [ 0.9734,  0.1366, -1.2498,  0.9046,  0.1522],
          [-0.7868,  0.4036, -2.0996,  0.5247, -1.4623]],

         [[-0.1174,  1.1110,  0.3674,  1.0821, -0.9075],
          [-0.7835,  1.0588, -1.9967, -0.9892,  1.5006],
          [ 0.5812, -1.2506,  1.3620, -0.2887,  0.8735],
          [-1.1874, -0.1137, -0.8554, -0.0490, -1.2590]],

         [[-1.5438,  0.4388, -0.0853,  0.0653,  0.3369],
          [ 0.1248,  1.1597,  2.4696,  0.2703,  0.1648],
          [ 0.5243, -1.2261, -0.4959, -0.8976, -1.9304],
          [-0.8943,  0.7186, -0.0715, -0.8624, -0.4985]]],


        [[[ 0.0281,  0.5425,  1.4867, -0.3844, -0.4928],
          [-1.1424,  0.1128, -1.3787,  2.4512, -0.0623],
          [ 0.8655,  0.6074, -0.8539, -1.6330,  1.1612],
          [ 1.0674,  0.8229, -0.3970, -0.1278,  0.4910]],

         [[-1.1861, -0.3424, -1.6311,  1.2168,  0.7684],
          [ 0.1363, -

## torch.utils.data.DataLoader
* Description : The torch.utils.data.DataLoader method creates a data loader to load datasets in batches

In [58]:
from torch.utils.data import DataLoader, TensorDataset

# Define a simple dataset
data = torch.randn(100, 2)
targets = torch.randn(100, 1)
dataset = TensorDataset(data, targets)

# Create a data loader
data_loader = DataLoader(dataset, batch_size=10, shuffle=True)

# Iterate trough the data loader
for batch_data, batch_targets in data_loader:
  print(batch_data.size(), batch_targets.size())

torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])
torch.Size([10, 2]) torch.Size([10, 1])


## torch.utils.data.Dataset
* Description : The torch.utils.data.Dataset method is an abstract class representing a dataset

In [59]:
from torch.utils.data import Dataset

# Define a custom dataset
class CustomDataset(Dataset):
  def __init__(self, data, targets):
    self.data = data
    self.targets = targets

  def __len__(self):
    return len(self.data)

  def __getitem__(self, index):
    return self.data[index], self.tagets[index]

# Create a dataset
data = torch.randn(100, 2)
targets = torch.randn(100, 1)
dataset = TensorDataset(data, targets)

# Get the length of the dataset
print(len(dataset))

# Get the first item from the dataset
print(dataset[0])

100
(tensor([0.5393, 0.4414]), tensor([1.9416]))


# Simple Linear Regression

In [60]:
import torch
import torch.nn as nn
import torch.optim as optim

In [61]:
# Create a dataset
x_train = torch.tensor([[1.0],[2.0],[3.0],[4.0]])
y_train = torch.tensor([[2.0],[4.0],[6.0],[8.0]])

# Define a linear model
model = nn.Linear(in_features=1, out_features=1)

# Define loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
for epoch in range(100):
  # Forward pass
  y_pred = model(x_train)

  # Compute loss
  loss = criterion(y_pred, y_train)

  # Backward pass and optimize
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

# Print model parameters
print(f'Weights: {model.weight.item()}, Bias: {model.bias.item()}')

Epoch: 1, Loss: 26.034957885742188
Epoch: 2, Loss: 18.070690155029297
Epoch: 3, Loss: 12.544422149658203
Epoch: 4, Loss: 8.709827423095703
Epoch: 5, Loss: 6.049048900604248
Epoch: 6, Loss: 4.202760696411133
Epoch: 7, Loss: 2.921626091003418
Epoch: 8, Loss: 2.0326414108276367
Epoch: 9, Loss: 1.415762186050415
Epoch: 10, Loss: 0.9876905679702759
Epoch: 11, Loss: 0.6906288862228394
Epoch: 12, Loss: 0.4844725728034973
Epoch: 13, Loss: 0.3413935899734497
Epoch: 14, Loss: 0.24208271503448486
Epoch: 15, Loss: 0.17314209043979645
Epoch: 16, Loss: 0.12527483701705933
Epoch: 17, Loss: 0.09203003346920013
Epoch: 18, Loss: 0.06893149018287659
Epoch: 19, Loss: 0.0528736412525177
Epoch: 20, Loss: 0.041701193898916245
Epoch: 21, Loss: 0.03391900286078453
Epoch: 22, Loss: 0.028489192947745323
Epoch: 23, Loss: 0.024691997095942497
Epoch: 24, Loss: 0.022027747705578804
Epoch: 25, Loss: 0.020149869844317436
Epoch: 26, Loss: 0.018817724660038948
Epoch: 27, Loss: 0.01786450855433941
Epoch: 28, Loss: 0.0171

# Multilayer Perceptron for Classification

In [62]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [63]:
# Create a classification dataset
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert to PyTorch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).unsqueeze(1)
y_test = torch.tensor(y_test, dtype=torch.float32).unsqueeze(1)

# Define a multilayer perceptron model
class MLP(nn.Module):
  def __init__(self):
    super(MLP, self).__init__()
    self.fc1 = nn.Linear(20, 64)
    self.fc2 = nn.Linear(64, 64)
    self.fc3 = nn.Linear(64, 1)
    self.relu = nn.ReLU()
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    x = self.relu(self.fc1(x))
    x = self.relu(self.fc2(x))
    x = self.sigmoid(self.fc3(x))
    return x

# Instantiate the model, define loss and optimizer
model = MLP()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
for epoch in range(100):
  # Forward pass
  y_pred = model(X_train)

  # Compute loss
  loss = criterion(y_pred, y_train)

  # Backward pass optimize
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

# Evaluate the model
with torch.no_grad():
  y_pred_test = model(X_test)
  y_pred_label = y_pred_test.round()
  accuracy = (y_pred_label.eq(y_test).sum() / y_test.shape[0]).item()
  print(f"Test Accuracy: {accuracy * 100:.2f}%")

Epoch: 1, Loss: 0.690386950969696
Epoch: 2, Loss: 0.6851776242256165
Epoch: 3, Loss: 0.6800220012664795
Epoch: 4, Loss: 0.6748710870742798
Epoch: 5, Loss: 0.6697039604187012
Epoch: 6, Loss: 0.6644928455352783
Epoch: 7, Loss: 0.6591967940330505
Epoch: 8, Loss: 0.6537772417068481
Epoch: 9, Loss: 0.6482372283935547
Epoch: 10, Loss: 0.6425454020500183
Epoch: 11, Loss: 0.6366557478904724
Epoch: 12, Loss: 0.630556046962738
Epoch: 13, Loss: 0.6242156028747559
Epoch: 14, Loss: 0.6176191568374634
Epoch: 15, Loss: 0.6107794046401978
Epoch: 16, Loss: 0.6037126183509827
Epoch: 17, Loss: 0.5963937640190125
Epoch: 18, Loss: 0.5888208746910095
Epoch: 19, Loss: 0.5809733271598816
Epoch: 20, Loss: 0.572858989238739
Epoch: 21, Loss: 0.5644861459732056
Epoch: 22, Loss: 0.5558735132217407
Epoch: 23, Loss: 0.5470138192176819
Epoch: 24, Loss: 0.5379208326339722
Epoch: 25, Loss: 0.528632402420044
Epoch: 26, Loss: 0.519168496131897
Epoch: 27, Loss: 0.5095350742340088
Epoch: 28, Loss: 0.4997621178627014
Epoch:

# Convolutional Neural Network for Image Classification

In [64]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

In [65]:
# Define a Simple CNN Model
class SimpleCNN(nn.Module):
  def __init__(self):
    super(SimpleCNN, self).__init__()
    self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)
    self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
    self.fc1 = nn.Linear(64*7*7, 128)
    self.fc2 = nn.Linear(128, 10)
    self.relu = nn.ReLU()
    self.maxpool = nn.MaxPool2d(kernel_size=2, stride=2)
    self.dropout = nn.Dropout(0.5)

  def forward(self, x):
    x = self.relu(self.conv1(x))
    x = self.maxpool(x)
    x = self.relu(self.conv2(x))
    x = self.maxpool(x)
    x = x.view(-1, 64*7*7)
    x = self.relu(self.fc1(x))
    x = self.dropout(x)
    x = self.fc2(x)
    return x

# Prepare the dataset and data loader
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
train_dataset = torchvision.datasets.MNIST(root= './data', train=True, transform=transform, download=True)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)

# Instantiate the model, define loss and optimizer
model = SimpleCNN()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
for epoch in range(5):
  for batch_idx, (data, target) in enumerate(train_loader):
    # Forward pass
    output = model(data)

    # Compute loss
    loss = criterion(output, target)

    # Backward pass optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if batch_idx % 100 == 0:
      print(f'Epoch: {epoch+1}, Batch: {batch_idx+1}, Loss: {loss.item()}')


Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9.91M/9.91M [00:00<00:00, 14.4MB/s]


Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28.9k/28.9k [00:00<00:00, 460kB/s]


Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1.65M/1.65M [00:00<00:00, 4.02MB/s]


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4.54k/4.54k [00:00<00:00, 6.80MB/s]


Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw

Epoch: 1, Batch: 1, Loss: 2.3187248706817627
Epoch: 1, Batch: 101, Loss: 0.5618106126785278
Epoch: 1, Batch: 201, Loss: 0.3069362938404083
Epoch: 1, Batch: 301, Loss: 0.29801273345947266
Epoch: 1, Batch: 401, Loss: 0.15818212926387787
Epoch: 1, Batch: 501, Loss: 0.3519284129142761
Epoch: 1, Batch: 601, Loss: 0.17800453305244446
Epoch: 1, Batch: 701, Loss: 0.08538595587015152
Epoch: 1, Batch: 801, Loss: 0.044815268367528915
Epoch: 1, Batch: 901, Loss: 0.03169817849993706
Epoch: 2, Batch: 1, Loss: 0.12648239731788635
Epoch: 2, Batch: 101, Loss: 0.04987381771206856
Epoch: 2, Batch: 201, Loss: 0.11632554978132248
Epoch: 2, Batch: 301, Loss: 0.33757394552230835
Epoch: 2, Batch: 401, Loss: 0.1065731942653656
Epoch: 2, Batch: 501, Loss: 0.17835113406181335
Epoch: 2, Batch: 601, Loss: 0.10117293149232864
Epoch: 2, Batch: 701, Loss: 0.020709656178951263
Epoch: 2, Batch: 801, Loss: 0.03745884448289871
Epoch: 2, Batch: 901

# Transfer Learning with Pretrained Models

In [66]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

In [67]:
# Load a pretrained ResNet18 model
model = torchvision.models.resnet18(pretrained=True)

# Freeze all layers except the final layer
for param in model.parameters():
  param.requires_grad = False

# Replace the final layer with a new fully connected layer
model.fc = nn.Linear(model.fc.in_features, 10)

# Prepare the dataset and data loader
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
train_dataset = torchvision.datasets.CIFAR10(root= './data', train=True, transform=transform, download=True)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)

# Define loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.fc.parameters(), lr=0.001)

# Training loop
for epoch in range(5):
  for batch_idx, (data, target) in enumerate(train_loader):
    # Forward pass
    output = model(data)

    # Compute loss
    loss = criterion(output, target)

    # Backward pass optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if batch_idx % 100 == 0:
      print(f'Epoch: {epoch+1}, Batch: {batch_idx+1}, Loss: {loss.item()}')

/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 89.8MB/s]


100%|██████████| 170M/170M [00:04<00:00, 41.9MB/s]


Extracting ./data/cifar-10-python.tar.gz to ./data
Epoch: 1, Batch: 1, Loss: 2.7112956047058105
Epoch: 1, Batch: 101, Loss: 1.8503146171569824
Epoch: 1, Batch: 201, Loss: 1.8362411260604858
Epoch: 1, Batch: 301, Loss: 1.6188535690307617
Epoch: 1, Batch: 401, Loss: 1.3484179973602295
Epoch: 1, Batch: 501, Loss: 1.5967048406600952
Epoch: 1, Batch: 601, Loss: 1.8243507146835327
Epoch: 1, Batch: 701, Loss: 1.3269680738449097
Epoch: 2, Batch: 1, Loss: 1.8344467878341675
Epoch: 2, Batch: 101, Loss: 1.6329410076141357
Epoch: 2, Batch: 201, Loss: 1.623386263847351
Epoch: 2, Batch: 301, Loss: 1.618338942527771
Epoch: 2, Batch: 401, Loss: 1.7516114711761475
Epoch: 2, Batch: 501, Loss: 1.551397681236267
Epoch: 2, Batch: 601, Loss: 1.6924344301223755
Epoch: 2, Batch: 701, Loss: 1.576602578163147
Epoch: 3, Batch: 1, Loss: 1.3825010061264038
Epoch: 3, Batch: 101, Loss: 1.279874324798584
Epoch: 3, Batch: 201, Loss: 1.4278780221939087
Epoch: 3, Batch: 301, Loss: 1.4697835445404053
Epoch: 3, Batch: 401

# Recurrent Neural Network for Sequence Modeling

In [71]:
import torch
import torch.nn as nn
import torch.optim as optim

In [72]:
# Define a Simple RNN Model
class SimpleRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleRNN, self).__init__()
        self.hidden_size = hidden_size
        self.rnn = nn.RNN(input_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        h0 = torch.zeros(1, x.size(0), self.hidden_size).to(x.device)
        out, _ = self.rnn(x, h0)
        out = self.fc(out[:, -1, :])
        return out

# Create some dummy data
x_train = torch.randn(100, 10, 1)  # 100 sequences of length 10
y_train = torch.randn(100, 1)      # 100 target values

# Instantiate the model, define loss and optimizer
model = SimpleRNN(input_size=1, hidden_size=20, output_size=1)
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
for epoch in range(100):
    # Forward pass
    y_pred = model(x_train)

    # Compute loss
    loss = criterion(y_pred, y_train)

    # Backward pass and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.9574964642524719
Epoch: 2, Loss: 0.9206814765930176
Epoch: 3, Loss: 0.9063995480537415
Epoch: 4, Loss: 0.9062814116477966
Epoch: 5, Loss: 0.9085456728935242
Epoch: 6, Loss: 0.9051200747489929
Epoch: 7, Loss: 0.8992499709129333
Epoch: 8, Loss: 0.8952388763427734
Epoch: 9, Loss: 0.8946941494941711
Epoch: 10, Loss: 0.8961865305900574
Epoch: 11, Loss: 0.896555483341217
Epoch: 12, Loss: 0.8951873183250427
Epoch: 13, Loss: 0.893237292766571
Epoch: 14, Loss: 0.8912220597267151
Epoch: 15, Loss: 0.8892372250556946
Epoch: 16, Loss: 0.8875116109848022
Epoch: 17, Loss: 0.8861852288246155
Epoch: 18, Loss: 0.8848648071289062
Epoch: 19, Loss: 0.8828138113021851
Epoch: 20, Loss: 0.8799920678138733
Epoch: 21, Loss: 0.8768643140792847
Epoch: 22, Loss: 0.8732627034187317
Epoch: 23, Loss: 0.8684607148170471
Epoch: 24, Loss: 0.8621922135353088
Epoch: 25, Loss: 0.8546848893165588
Epoch: 26, Loss: 0.8454296588897705
Epoch: 27, Loss: 0.8377335071563721
Epoch: 28, Loss: 0.8312197923660278
Epo

# AutoEncoder for Dimensionality Reduction

In [73]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

In [74]:
# Define a Simple AutoEncoder Model
class Autoencoder(nn.Module):
  def __init__(self):
    super(Autoencoder, self).__init__()
    self.encoder = nn.Sequential(
        nn.Linear(784, 256),
        nn.ReLU(),
        nn.Linear(256, 64),
        nn.ReLU(),
        nn.Linear(64, 12),
        nn.ReLU(),
        nn.Linear(12, 3)
    )
    self.decoder = nn.Sequential(
        nn.Linear(3, 12),
        nn.ReLU(),
        nn.Linear(12, 64),
        nn.ReLU(),
        nn.Linear(64, 256),
        nn.ReLU(),
        nn.Linear(256, 784),
        nn.Sigmoid()
    )
  def forward(self, x):
    x = self.encoder(x)
    x = self.decoder(x)
    return x

# Load the MNIST dataset
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
train_dataset = datasets.MNIST(root= './data', train=True, transform=transform, download=True)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)

# Instantiate the model, define loss and optimizer
model = Autoencoder()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
for epoch in range(5):
  for batch_idx, (data, _) in enumerate(train_loader):
    # Flatten the data
    data = data.view(-1, 784)

    # Forward pass
    output = model(data)

    # Compute loss
    loss = criterion(output, data)

    # Backward pass optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if batch_idx % 100 == 0:
      print(f'Epoch: {epoch+1}, Batch: {batch_idx+1}, Loss: {loss.item()}')

Epoch: 1, Batch: 1, Loss: 1.9401276111602783
Epoch: 1, Batch: 101, Loss: 0.9247053265571594
Epoch: 1, Batch: 201, Loss: 0.924060583114624
Epoch: 1, Batch: 301, Loss: 0.926344633102417
Epoch: 1, Batch: 401, Loss: 0.9255186319351196
Epoch: 1, Batch: 501, Loss: 0.9242287278175354
Epoch: 1, Batch: 601, Loss: 0.9252778887748718
Epoch: 1, Batch: 701, Loss: 0.9248301982879639
Epoch: 1, Batch: 801, Loss: 0.9234321713447571
Epoch: 1, Batch: 901, Loss: 0.9239531755447388
Epoch: 2, Batch: 1, Loss: 0.9264110922813416
Epoch: 2, Batch: 101, Loss: 0.9275420904159546
Epoch: 2, Batch: 201, Loss: 0.9251922369003296
Epoch: 2, Batch: 301, Loss: 0.9264194965362549
Epoch: 2, Batch: 401, Loss: 0.9246658086776733
Epoch: 2, Batch: 501, Loss: 0.9301068186759949
Epoch: 2, Batch: 601, Loss: 0.9240251779556274
Epoch: 2, Batch: 701, Loss: 0.9240109920501709
Epoch: 2, Batch: 801, Loss: 0.9282069206237793
Epoch: 2, Batch: 901, Loss: 0.9280322194099426
Epoch: 3, Batch: 1, Loss: 0.9243888258934021
Epoch: 3, Batch: 101,

# Generative Adversarial Network (GAN) for Image Generation

In [75]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
from torchvision.transforms import transforms
from torch.utils.data import DataLoader

In [76]:
# Define the generator model
class Generator(nn.Module):
    def __init__(self, z_dim):
        super(Generator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(z_dim, 256),
            nn.ReLU(),
            nn.Linear(256, 512),
            nn.ReLU(),
            nn.Linear(512, 1024),
            nn.ReLU(),
            nn.Linear(1024, 784),
            nn.Tanh()
        )

    def forward(self, x):
        return self.model(x)

# Define the discriminator model
class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(784, 1024),
            nn.LeakyReLU(0.2),
            nn.Linear(1024, 512),
            nn.LeakyReLU(0.2),
            nn.Linear(512, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

# Hyperparameters
z_dim = 64
batch_size = 64
lr = 0.0002

# Load the MNIST dataset
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
train_dataset = torchvision.datasets.MNIST(root='./data', train=True, transform=transform, download=True)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

# Instantiate the models and optimizers
generator = Generator(z_dim)
discriminator = Discriminator()
g_optimizer = optim.Adam(generator.parameters(), lr=lr)
d_optimizer = optim.Adam(discriminator.parameters(), lr=lr)
criterion = nn.BCELoss()

# Training loop
for epoch in range(5):
    for batch_idx, (real_images, _) in enumerate(train_loader):
        # Train the discriminator
        real_images = real_images.view(-1, 784)
        real_labels = torch.ones(real_images.size(0), 1)
        fake_labels = torch.zeros(real_images.size(0), 1)

        d_optimizer.zero_grad()
        outputs = discriminator(real_images)
        real_loss = criterion(outputs, real_labels)
        real_loss.backward()

        z = torch.randn(real_images.size(0), z_dim)
        fake_images = generator(z)
        outputs = discriminator(fake_images.detach())
        fake_loss = criterion(outputs, fake_labels)
        fake_loss.backward()
        d_optimizer.step()

        # Train the generator
        g_optimizer.zero_grad()
        z = torch.randn(real_images.size(0), z_dim)
        fake_images = generator(z)
        outputs = discriminator(fake_images)
        g_loss = criterion(outputs, real_labels)
        g_loss.backward()
        g_optimizer.step()

        # Print the progress
        if batch_idx % 100 == 0:
            print(f'Epoch: {epoch+1}, Batch: {batch_idx+1}, D_Loss: {real_loss.item() + fake_loss.item()}, G_Loss: {g_loss.item()}')


Epoch: 1, Batch: 1, D_Loss: 1.3698039054870605, G_Loss: 0.7255949378013611
Epoch: 1, Batch: 101, D_Loss: 0.6966733266599476, G_Loss: 1.315826654434204
Epoch: 1, Batch: 201, D_Loss: 0.05847282148897648, G_Loss: 4.69512939453125
Epoch: 1, Batch: 301, D_Loss: 2.2643869519233704, G_Loss: 6.669920444488525
Epoch: 1, Batch: 401, D_Loss: 0.10655095428228378, G_Loss: 8.54127025604248
Epoch: 1, Batch: 501, D_Loss: 0.4716063588857651, G_Loss: 9.711624145507812
Epoch: 1, Batch: 601, D_Loss: 0.008309667930006981, G_Loss: 8.433843612670898
Epoch: 1, Batch: 701, D_Loss: 0.19639632292091846, G_Loss: 6.885838508605957
Epoch: 1, Batch: 801, D_Loss: 0.9398174285888672, G_Loss: 5.788382053375244
Epoch: 1, Batch: 901, D_Loss: 0.014115361496806145, G_Loss: 12.57106876373291
Epoch: 2, Batch: 1, D_Loss: 0.03086218192765955, G_Loss: 9.052335739135742
Epoch: 2, Batch: 101, D_Loss: 0.012346431380137801, G_Loss: 5.5352559089660645
Epoch: 2, Batch: 201, D_Loss: 0.01337520481320098, G_Loss: 9.844219207763672
Epoch

# Sequence to Sequence Model for Translation

In [77]:
import torch
import torch.nn as nn
import torch.optim as optim

In [78]:
# Define an encoder-decoder model
class Seq2Seq(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(Seq2Seq, self).__init__()
        self.encoder = nn.RNN(input_dim, hidden_dim, batch_first=True)
        self.decoder = nn.RNN(hidden_dim, output_dim, batch_first=True)

    def forward(self, x):
        # Encode the input sequence
        _, hidden = self.encoder(x)  # hidden: [1, batch_size, hidden_dim]

        # Repeat hidden state for all time steps
        hidden_repeated = hidden.repeat(x.size(1), 1, 1).permute(1, 0, 2)

        # Decode using the repeated hidden state
        output, _ = self.decoder(hidden_repeated)
        return output

# Create some dummy data
x_train = torch.randn(100, 10, 5)  # 100 sequences of length 10 with 5 features
y_train = torch.randn(100, 10, 3)  # 100 sequences of length 10 with 3 features

# Instantiate the model, define loss and optimizer
input_dim = 5
hidden_dim = 20
output_dim = 3
model = Seq2Seq(input_dim=input_dim, hidden_dim=hidden_dim, output_dim=output_dim)

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
for epoch in range(100):
    model.train()

    # Forward pass
    y_pred = model(x_train)

    # Compute loss
    loss = criterion(y_pred, y_train)

    # Backward pass and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')


Epoch: 1, Loss: 1.3762903213500977
Epoch: 2, Loss: 1.238774299621582
Epoch: 3, Loss: 1.1877046823501587
Epoch: 4, Loss: 1.148733377456665
Epoch: 5, Loss: 1.0890756845474243
Epoch: 6, Loss: 1.0568042993545532
Epoch: 7, Loss: 1.0537418127059937
Epoch: 8, Loss: 1.0509737730026245
Epoch: 9, Loss: 1.0434114933013916
Epoch: 10, Loss: 1.0383517742156982
Epoch: 11, Loss: 1.0367317199707031
Epoch: 12, Loss: 1.0341196060180664
Epoch: 13, Loss: 1.0289456844329834
Epoch: 14, Loss: 1.0230926275253296
Epoch: 15, Loss: 1.0184237957000732
Epoch: 16, Loss: 1.015229344367981
Epoch: 17, Loss: 1.013109564781189
Epoch: 18, Loss: 1.0117244720458984
Epoch: 19, Loss: 1.0106925964355469
Epoch: 20, Loss: 1.0094670057296753
Epoch: 21, Loss: 1.0076595544815063
Epoch: 22, Loss: 1.0054506063461304
Epoch: 23, Loss: 1.0034857988357544
Epoch: 24, Loss: 1.0022796392440796
Epoch: 25, Loss: 1.0017480850219727
Epoch: 26, Loss: 1.0013526678085327
Epoch: 27, Loss: 1.0006507635116577
Epoch: 28, Loss: 0.9996250867843628
Epoch